# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  # color: emerald
  theme_day: minimal
  # theme_night: minimal
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Chris Lindgren an Assistant Professor of Technical Communication & Data Visualization in the English Department at Virginia Tech. Research fields include critical data studies, communication design, Indigenous Data Sovereignty, and coding literacy.'
    twitter: 'lndgrn'
  analytics:
    google_analytics: 'G-69ZB7R7HVQ'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: center
    show_logo: true
    logo:
      filename: icon.png
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    # logo:
    #   text: "Your Name"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  syntax_highlighter:
    enable: true
    extra_languages:
      - python
      - r
      - latex
  repository:
    url: 'https://github.com/lingeringcode/clndgrn-portfolio'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true